# Generated by Django 5.0.6 on 2024-06-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translater',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
