# Generated by Django 5.0.6 on 2024-06-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_translater_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
