# Generated by Django 5.0.6 on 2024-07-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_language_alter_product_rating_alter_product_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='language',
        ),
    ]
