# Generated by Django 5.0.6 on 2024-07-01 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_product_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.language'),
        ),
    ]
