# Generated by Django 5.0.6 on 2024-07-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_yearperiod_product_added_product_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
